[WIP] GlobalEval
bowen-xu/PyNARS pull request #28
Opened 2023-09-21 21:20 UTC by bowen-xu

2023-11-09 00:36 UTC, bowen-xu commented
@maxeeem could you please help to review the code when you get a chance?

2023-11-09 00:44 UTC, bowen-xu commented
Locations where the for evaluators are updated:
**Satisfaction**
https://github.com/bowen-xu/PyNARS/blob/704a9b9b4e110016e9d79059c099ed6a8a0d9621/pynars/NARS/DataStructures/_py/Memory.py#L367-L367

https://github.com/bowen-xu/PyNARS/blob/704a9b9b4e110016e9d79059c099ed6a8a0d9621/pynars/NARS/DataStructures/_py/Memory.py#L391-L391

**Busyness**
https://github.com/bowen-xu/PyNARS/blob/704a9b9b4e110016e9d79059c099ed6a8a0d9621/pynars/NARS/Control/Reasoner.py#L122-L123

**Alertness**
https://github.com/bowen-xu/PyNARS/blob/704a9b9b4e110016e9d79059c099ed6a8a0d9621/pynars/NARS/Control/Reasoner.py#L126-L139

**Well-being**
https://github.com/bowen-xu/PyNARS/blob/704a9b9b4e110016e9d79059c099ed6a8a0d9621/pynars/NARS/Control/Reasoner.py#L216-L217

2023-12-06 00:16 UTC, maxeeem commented
@bowen-xu there seems to be a conflict with the dev branch which will need to be resolved before merging

2023-12-06 01:08 UTC, maxeeem commented on pynars/NARS/Control/Reasoner.py
> +            self.global_eval.update_wellbeing(task_executed.truth.e)
This is currently inside the `mental_operation` function. Is it just the name or is there another function elsewhere for other types of operations? 

The reason I ask is if `well-being` is meant to represent the 'body' functioning as expected, then it seems more related to operations like ^move or ^look etc rather than mental operations.

2023-12-06 01:08 UTC, maxeeem commented on pynars/NARS/DataStructures/_py/Memory.py
> +        self.global_eval.update_satisfaction(task.achieving_level(belief.truth), task.budget.priority)
We should probably add this to questions as well in addition to goals. But perhaps later, not in this initial PR.

2023-12-06 01:08 UTC, maxeeem commented on pynars/NARS/Control/Reasoner.py
> +            self.global_eval.update_alertness(judgement_revised.truth.c - task.truth.c)
Should this be an absolute value to avoid negative numbers?

2023-12-07 02:13 UTC, bowen-xu commented on pynars/NARS/Control/Reasoner.py
> +            self.global_eval.update_alertness(judgement_revised.truth.c - task.truth.c)
`judgement_revised.truth.c - task.truth.c` could be negative

2023-12-07 02:18 UTC, bowen-xu commented on pynars/NARS/Control/Reasoner.py
> +            self.global_eval.update_wellbeing(task_executed.truth.e)
Oh u r right. Since there is no "body" in the current implementation, Pei told me that we can tentatively update `well-being` when an operation is succesfully executed. So this should also be called when any operations (like ^move and ^look) are executed.

2023-12-09 16:26 UTC, ccrock4t requested changes

2023-12-09 16:26 UTC, ccrock4t commented on pynars/NARS/Control/Reasoner.py
> +            self.global_eval.update_busyness(task.budget.priority)
Good

2023-12-09 16:26 UTC, ccrock4t commented on pynars/NARS/Control/Reasoner.py
> +                judgement_revised.truth.c - task.truth.c)
I see this cannot be implemented as written until we have anticipations / EventBuffer. 

But if we merge this and wait, we might forget to implement the Alertness properly. To remedy this, we need to create another Github Issue to remind us, OR wait to merge this PR until we have Anticipations

2023-12-09 16:26 UTC, ccrock4t commented on pynars/NARS/Control/Reasoner.py
> +                judgement_revised.truth.c - task.truth.c)
To roughly analyze the current code:

- If the task is _low_ confidence + the belief is _low_ confidence = the revised belief is _medium_ confidence + alertness is _low_
- If the task is _low_ confidence + the belief is _high_ confidence = the revised belief is _high_ confidence + alertness is _medium_
- If the task is _high_ confidence + the belief is _low_ confidence = the revised belief is _high_ confidence + alertness is _low_
- If the task is _high_ confidence + the belief is _high_ confidence = the revised belief is _high_ confidence + alertness is _low_

2023-12-09 16:26 UTC, ccrock4t commented on pynars/NARS/DataStructures/_py/Memory.py
> +        self.global_eval.update_satisfaction(task.achieving_level(belief.truth), task.budget.priority)
Matches

2023-12-09 16:26 UTC, ccrock4t commented on pynars/NARS/GlobalEval.py
> +class GlobalEval:
Where did these formulas come from? Should we add them to the report?

2023-12-09 16:30 UTC, ccrock4t commented on pynars/NARS/Control/Reasoner.py
> +            self.global_eval.update_alertness(judgement_revised.truth.c - task.truth.c)
Since the Revision rule always increases confidence, the Task's Judgment would always be lower confidence than the revised Judgment

2023-12-21 04:27 UTC, bowen-xu commented on pynars/NARS/GlobalEval.py
> +class GlobalEval:
They are from this paper https://cis.temple.edu/~pwang/Publication/emotion.pdf

<img width="647" alt="image" src="https://github.com/bowen-xu/PyNARS/assets/58252898/091b9831-ef5f-4954-a560-ffce35ab1897">

Here are some related discriptions:

https://cis.temple.edu/~pwang/Publication/emotion.pdf
<img width="939" alt="image" src="https://github.com/bowen-xu/PyNARS/assets/58252898/be45b1a0-ed53-4f45-b7c8-2c24e4530168">

https://cis.temple.edu/tagit/publications/PAGI-TR-11.pdf
<img width="1019" alt="image" src="https://github.com/bowen-xu/PyNARS/assets/58252898/2c531a41-15a7-46ac-aa65-2c1f51c8eedd">

2023-12-21 04:28 UTC, bowen-xu commented on pynars/NARS/Control/Reasoner.py
> +                judgement_revised.truth.c - task.truth.c)
> I see this cannot be implemented as written until we have anticipations / EventBuffer.
> 
> But if we merge this and wait, we might forget to implement the Alertness properly. To remedy this, we need to create another Github Issue to remind us, OR wait to merge this PR until we have Anticipations

Absolutely! We need something to remind us in the future.

2023-12-22 20:33 UTC, ccrock4t commented on pynars/NARS/Control/Reasoner.py
> +                judgement_revised.truth.c - task.truth.c)
Added in #86

2023-12-22 20:46 UTC, ccrock4t approved these changes

2023-12-23 18:58 UTC, bowen-xu commented
> @bowen-xu there seems to be a conflict with the dev branch which will need to be resolved before merging

@maxeeem Fixed.

2023-12-26 16:34 UTC, merged